---
title: 异步编程
author: “zhangxin”
date: 2023-07-27 16:58:17
tags: python
categories: python
---

# python asyncio并发编程

### asyncio基础

#### 1.通过任务实现并发

```python
import asyncio


async def delay(delay_seconds: int) -> int:
    print(f"等待{delay_seconds}秒")
    await asyncio.sleep(delay_seconds)
    print(f"完成等待{delay_seconds}秒")
    return delay_seconds
```

```python
import asyncio
from util import delay


async def hello_every_second():
    for i in range(2):
        await asyncio.sleep(1)
        print('我在等待时正在运行其他代码')


async def main():
    fist_delay = asyncio.create_task(delay(3))
    second_delay = asyncio.create_task(delay(3))
    await hello_every_second()
    await fist_delay
    await second_delay


if __name__ == '__main__':
    asyncio.run(main())

```

代码时间运行过程:

![](https://raw.githubusercontent.com/ai-Iverson/images/main/202307271751241.png)

#### 2.取消任务和设置超时

- 取消任务

  每个任务对象都有一个名为cancel的方法,可以想要停止任务时调用它,取消一个任务将导致该任务在执行await时引发CancelledErrorr然后可以根据需要处理它

  ```python
  import asyncio
  from asyncio import CancelledError
  from util import delay
  
  
  async def main():
      long_task = asyncio.create_task(delay(10))
  
      second_elapsed = 0
      while not long_task.done():
          print("任务未完成")
          # await 会触发其他时间循环中的task执行
          await asyncio.sleep(1)
          second_elapsed = second_elapsed + 1
          if second_elapsed == 5:
              long_task.cancel()
  
      try:
          await long_task
      except CancelledError:
          print("任务取消")
  
  
  asyncio.run(main())
  
  ```

  我们创建了一个任务，它将花费10 秒的时间来运行。然后 创建 一个while循环来检查该任务是否已完成。任务的done方法在任务完成时返回 True，否则返回False。每 一秒，我们检查任务是否已经完成，并记录到目前为止经历 了多少秒。如果任务已经花费了5秒，就取消这个任务。然后来到await long task，将输出任务取消 ， 这 表 明 捕 获 了一 个 CancelledError

  

- 使用wait_for设置超时任务取消

  ```python
  import asyncio
  from util import delay
  
  
  async def main():
      delay_task = asyncio.create_task(delay(2))
      try:
          result = await asyncio.wait_for(delay_task, timeout=1)
          print(result)
      except asyncio.exceptions.TimeoutError:
          print("任务超时")
  
  
  asyncio.run(main())
  
  ```

- 使用asyncio.shield保护任务免于取消

  ```python
  async def main():
      delay_task = asyncio.create_task(delay(2))
      try:
          result = await asyncio.wait_for(asyncio.shield(delay_task), timeout=1)
          print(result)
      except asyncio.exceptions.TimeoutError:
          print("任务超时")
          result = await delay_task
          print(result)
  ```

  

#### 3.任务,协程,future和awaitable

- 什么是future?

  - future 是一个 Python 对象，它包含一个你希望在未来某个时间点获得但目前可能 还不存在的值。通常，当创建future 时，它没有任何值，因为它还不存在。在这种状 态下，它被认为是不完整的、未解决的或根本没有完成的。然后， 一旦你得到 一个结 果，就可以设置future 的值，这将完成future。那时，我们可以认为它已经完成,并可 从 future提取结果 

- 等待一个future

  ```python
  from asyncio import Future
  import asyncio
  
  
  async def set_future_value(future) -> None:
      await asyncio.sleep(1)
      future.set_result(42)
  
  
  def make_request() -> Future:
      future = Future()
      asyncio.create_task(set_future_value(future))
      return future
  
  
  async def main():
      future = make_request()
      print(f"future is done? {future.done()}")
      value = await future
      print(f"future is done? {future.done()}")
      print(value)
  
  
  asyncio.run(main())
  ```



- Future ,任务和协程之间的关系

  ![](https://raw.githubusercontent.com/ai-Iverson/images/main/202307271751260.png)

​	创建一个任务时,我们正在创建一个空future,并运行协程,当协程以得到结果或异常结束时,我们将设置future的结果或异常



